import styles from '../styles/Home.module.scss'

import Head from 'next/head'
import Link from 'next/link'
import { motion } from "framer-motion"

export default function Home() {
    const variants = {
        hidden: { opacity: 0 },
        visible: { opacity: 1 }
    }

    return (
        <motion.div initial="hidden" animate="visible" exit="hidden" variants={variants} className={styles.container}>
            <Head>
                <title>YonicStudios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <img src="/ys_logo.svg" alt="YonicStudios Logo" className={styles.logo} width="900" heighr="300"/>
            <p>Making fantastic worlds since 2008.</p>
            <nav className={styles.navigation}>
                <Link href="/games"><a>Games</a></Link>
                <Link href="/animations"><a>Animations</a></Link>
            </nav>
        </motion.div>
    )
}
